version: '3.7'
services:
  node-red:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1880:1880"
    volumes:
      - ".:/data"
      - ".:/data/node_modules/@webfactorygmbh/node-red-contrib-i4connected-connector"